GET http://localhost:8080/currentUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiNGNiZjc5Zi03ZjI2LTRhNWItYWQ3ZC1jNTI1OWZlZmNlYmEiLCJpc3MiOiJDcnlwdG9QdWxzZVBsYXkiLCJhdWQiOiJVc2VyT25QbGF5Iiwic3ViIjoiam9zd3h4QGdtYWlsLmNvbSIsInVzZXJJZCI6MSwicHVycG9zZSI6ImxvZ2luQ2hlY2siLCJyb2xlIjoiVVNFUiIsImV4cCI6MTY5OTAxOTA5NH0.DgN5V_M5cf83r-59WCzO17jRWtFsFKeW8RKWeosRh5o
