POST http://localhost:8080/addPoint
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJjMGNjODZhNS1kMDRkLTRmYjktOWRmOC0zNGMwNzllNzY5MmEiLCJpc3MiOiJDcnlwdG9QdWxzZVBsYXkiLCJhdWQiOiJVc2VyT25QbGF5Iiwic3ViIjoiam9zd3h4QGdtYWlsLmNvbSIsInVzZXJJZCI6MSwicHVycG9zZSI

{
  "point": 30000
}







