POST http://localhost:8080/addPoint
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3N3eHhAZ21haWwuY29tIiwidXNlcklkIjoxLCJwdXJwb3NlIjoibG9naW5DaGVjayIsImV4cCI6MTY5NzcyNjA3MX0.ldoDG4ITpqfwgTuS0hAjdj-99fiWCWXHfRBbqLcUIWA

{
  "point": 10000
}






